// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADtL_xKOiJgw9Bg_PCPYTTAcXSvxzeqvQ',
    appId: '1:239647624541:web:141cd748d3f8f16749ecb4',
    messagingSenderId: '239647624541',
    projectId: 'campusconnect-b9c5b',
    authDomain: 'campusconnect-b9c5b.firebaseapp.com',
    storageBucket: 'campusconnect-b9c5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmw3nYGuE6iBIcMsoR2TdTeU-nDQMa9wo',
    appId: '1:239647624541:android:ee480b6a13a9517849ecb4',
    messagingSenderId: '239647624541',
    projectId: 'campusconnect-b9c5b',
    storageBucket: 'campusconnect-b9c5b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4iWilKikR7xbxDVQtYLeUzZjaCPdV7lU',
    appId: '1:239647624541:ios:b7dfa7e2ccbca68549ecb4',
    messagingSenderId: '239647624541',
    projectId: 'campusconnect-b9c5b',
    storageBucket: 'campusconnect-b9c5b.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4iWilKikR7xbxDVQtYLeUzZjaCPdV7lU',
    appId: '1:239647624541:ios:b7dfa7e2ccbca68549ecb4',
    messagingSenderId: '239647624541',
    projectId: 'campusconnect-b9c5b',
    storageBucket: 'campusconnect-b9c5b.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADtL_xKOiJgw9Bg_PCPYTTAcXSvxzeqvQ',
    appId: '1:239647624541:web:96a683ca2785d56b49ecb4',
    messagingSenderId: '239647624541',
    projectId: 'campusconnect-b9c5b',
    authDomain: 'campusconnect-b9c5b.firebaseapp.com',
    storageBucket: 'campusconnect-b9c5b.firebasestorage.app',
  );
}
